### ISSUE TITLE
Is this ready to use? 

### ISSUE THREAD

**Issue by kb1ooo** [arunpalaniappan/TadGAN#1]
Hi,  

Thanks for making this available.  I see that you just have one commit.  Is this ready to use?  

I will look more carefully at your paper, but does the technique work reasonably well for signals that very little to no periodic structure?  

Thanks

**Comment by arunpalaniappan** [comment]
Hi, 

1) I am not related to author of the papers.

2) The code is ready to use. I have added the usage section.

3) The code worked for the mentioned dataset. For other dataset, it might work as wll as suggested by the authors of the paper.

Thanks.
